#!/bin/bash -u

if realpath $0 | grep -v '\.git' > /dev/null; then
  echo not git
  git=$(dirname $0)/.git/
  cp $0 ${git}/merge
  exec ${git}/merge
fi

(
  git switch component-status
  git rebase up/main || exit 1
  git push -f
)
git stash -a
git stash clear
git switch main

git merge component-status
git merge fix-component_update
